### ISSUE TITLE
blocks_compressed.js: that is not definied

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/blockly#30]
Please re-build and merge the blocky components. The variable "that" is not defined in the compressed blocky build.
` ReferenceError: that is not defined [] blocks_compressed.js:104:152 
updatePorts /blockly/blocks_compressed.js:104 `

Thanks!

**Comment by VinArt** [comment]
@pablopoo Could you please specify where you have encountered the error? Which scenario, maybe provide the program that you used?

**Comment by pablopoo** [comment]
@VinArt 
1. Nepo4Arduino Uno
2. 
![imagen](https://user-images.githubusercontent.com/13492043/51759933-22166b80-20a8-11e9-8cdf-f6d581445baf.png)
3.add 2 write blocks
![imagen](https://user-images.githubusercontent.com/13492043/51760023-5722be00-20a8-11e9-9d8c-622c903191ce.png)
4. Try to switch one to analog
![imagen](https://user-images.githubusercontent.com/13492043/51760058-66a20700-20a8-11e9-815e-e0d4062c6e70.png)
5.
![imagen](https://user-images.githubusercontent.com/13492043/51760086-73265f80-20a8-11e9-97f6-9f202e3b3cc4.png)

**Comment by pablopoo** [comment]
@VinArt I just replaced the "that" variable with "this" in blocks_compressed.js to make it work:
![imagen](https://user-images.githubusercontent.com/13492043/51760406-20997300-20a9-11e9-974d-c25b38062cb0.png)

**Comment by VinArt** [comment]
@pablopoo thank you for the clarification.
